const cupCards = [
    { name: "ACE OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Cups01.jpg", meaning_reg: "사랑의 샘이 터져 나옵니다. 정서적인 충만함과 관계의 축복이 함께하니 마음껏 나누십시오.", meaning_rev: "감정이 메말라 있거나 자기 연민에 빠져 있습니다. 마음의 그릇을 비우고 진실된 감정을 마주하세요." },
    { name: "TWO OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Cups02.jpg", meaning_reg: "영혼의 파트너와 유대감이 깊어집니다. 존중과 조화가 깃든 대화가 원활하게 이루어지는 날입니다.", meaning_rev: "사소한 오해가 소통의 부재를 낳습니다. 자존심보다는 먼저 손을 내미는 용기가 관계를 살립니다." },
    { name: "THREE OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Cups03.jpg", meaning_reg: "공동체의 화합과 축하의 자리가 생깁니다. 기쁨을 나누면 배가 되니 함께 웃고 즐기십시오.", meaning_rev: "겉치레 관계에서 허무함을 느낍니다. 지나친 유흥이 당신의 에너지를 갉아먹고 있지는 않은가요?" },
    { name: "FOUR OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/3/35/Cups04.jpg", meaning_reg: "권태로운 기분에 사로잡혀 하늘의 기회도 놓치고 있군요. 내면으로 침잠하기보다 고개를 들어보세요.", meaning_rev: "무기력에서 벗어날 준비가 됐습니다. 새로운 자극이 찾아오니 마음의 빗장을 풀고 기회를 잡으십시오." },
    { name: "FIVE OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Cups05.jpg", meaning_reg: "쏟아진 잔을 보며 슬퍼하고 계시는군요. 뒤에 남은 두 잔의 희망을 보십시오. 슬픔 뒤엔 성장이 있습니다.", meaning_rev: "과거의 상처에서 회복되기 시작했습니다. 이제는 눈물을 닦고 남겨진 소중한 가치를 위해 움직이세요." },
    { name: "SIX OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/1/17/Cups06.jpg", meaning_reg: "과거의 순수했던 기억이나 옛 인연이 행운을 가져다줍니다. 동심으로 돌아가 마음을 정화하십시오.", meaning_rev: "추억에만 젖어 현실을 외면하고 있군요. 과거는 과거일 뿐, 오늘을 살아야 미래가 보입니다." },
    { name: "SEVEN OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Cups07.jpg", meaning_reg: "환상과 선택지가 너무 많아 혼란스럽습니다. 구름 위의 성을 쫓기보다 현실적인 가치를 고르십시오.", meaning_rev: "몽상에서 깨어납니다. 비현실적인 계획을 정리하고 이제는 명확한 목표를 세워 실천해야 할 때입니다." },
    { name: "EIGHT OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/6/60/Cups08.jpg", meaning_reg: "감정적인 만족을 찾아 미련 없이 떠날 때입니다. 익숙한 것을 뒤로하는 용기가 더 큰 성장을 줍니다.", meaning_rev: "떠나야 할 때를 놓치고 질척거리고 있습니다. 가망 없는 관계나 상황에 매달리는 이유를 돌아보세요." },
    { name: "NINE OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/2/24/Cups09.jpg", meaning_reg: "소원 성취의 카드입니다. 정서적, 물질적 만족감이 극에 달하니 충분히 행복을 누리십시오.", meaning_rev: "성취 뒤의 오만함이 화를 부릅니다. 겉으론 완벽해 보이나 내면의 공허함은 여전하니 겸손하십시오." },
    { name: "TEN OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Cups10.jpg", meaning_reg: "가정의 평화와 무지개 같은 행복이 찾아옵니다. 가장 소중한 사람들과 완벽한 결속을 이루십시오.", meaning_rev: "가까운 이들과의 갈등이 예상됩니다. 외적인 평화만 꾸미지 말고 서로의 진심을 먼저 보살피십시오." },
    { name: "PAGE OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Cups11.jpg", meaning_reg: "상상력이 풍부한 새로운 감정적 소식이 들려옵니다. 어린아이 같은 호기심으로 제안을 받아들이세요.", meaning_rev: "유치한 감정 싸움에 휘말릴 수 있습니다. 현실성 없는 제안에 현혹되지 않도록 감정을 다스리십시오." },
    { name: "KNIGHT OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Cups12.jpg", meaning_reg: "로맨틱하고 따뜻한 제안이 다가옵니다. 당신의 감정을 정중하게 전달하기에 아주 좋은 시기입니다.", meaning_rev: "감언이설을 주의하십시오. 지나치게 감상적인 태도가 현실의 문제를 그르칠 수 있으니 주의하세요." },
    { name: "QUEEN OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/6/62/Cups13.jpg", meaning_reg: "자애롭고 직관적인 에너지가 가득합니다. 주변을 치유하고 공감하는 능력이 큰 힘을 발휘할 것입니다.", meaning_rev: "감정의 기복이 심해지고 의존적이게 됩니다. 타인을 돌보기 전 당신의 마음부터 단단히 챙기십시오." },
    { name: "KING OF CUPS", img: "https://upload.wikimedia.org/wikipedia/commons/0/04/Cups14.jpg", meaning_reg: "감정의 바다를 다스리는 현자입니다. 차분하고 포용력 있는 태도가 모든 갈등을 해결할 것입니다.", meaning_rev: "냉정한 척하지만 속으로는 요동치고 있군요. 감정을 억누르기보다 건강하게 해소할 길을 찾으십시오." }
];