const pentacleCards = [
    { name: "ACE OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Pents01.jpg", meaning_reg: "현실적인 기회가 찾아옵니다. 새로운 재물이나 건강, 기반을 다질 수 있는 최고의 날입니다.", meaning_rev: "준비되지 않은 기회는 위기일 뿐입니다. 기초가 약한 계획은 결국 무너지니 내실을 먼저 다지십시오." },
    { name: "TWO OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Pents02.jpg", meaning_reg: "변화하는 상황 속에서 균형을 잡고 있군요. 유연한 대처가 당신을 위태로움에서 구할 것입니다.", meaning_rev: "감당하기 힘든 일을 동시에 벌이고 있습니다. 우선순위를 정하지 않으면 둘 다 놓치게 됩니다." },
    { name: "THREE OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/4/42/Pents03.jpg", meaning_reg: "협력과 전문성이 인정받는 날입니다. 함께 머리를 맞대면 장인과 같은 완벽한 성과를 낼 수 있습니다.", meaning_rev: "기초적인 기술 부족이나 협력 부진이 예상됩니다. 혼자 고집부리기보다 실력을 더 연마하십시오." },
    { name: "FOUR OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/3/35/Pents04.jpg", meaning_reg: "안정을 찾았으나 지나치게 소유에 집착하고 있군요. 쥐고만 있으면 새로운 흐름이 들어오지 못합니다.", meaning_rev: "재정적 손실이 우려되거나 혹은 지나친 인색함이 사람을 잃게 합니다. 마음의 곳간을 조금 여십시오." },
    { name: "FIVE OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/9/96/Pents05.jpg", meaning_reg: "재정적, 신체적 어려움을 겪을 수 있습니다. 하지만 바로 옆의 도움의 손길을 잊지 마십시오.", meaning_rev: "고난의 터널이 끝나갑니다. 잃어버린 기반을 다시 세울 실마리를 찾게 되니 희망을 가지십시오." },
    { name: "SIX OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Pents06.jpg", meaning_reg: "공평한 나눔과 보상이 이루어지는 날입니다. 베푼 만큼 돌아오고, 필요한 만큼 얻게 될 것입니다.", meaning_rev: "불평등한 거래나 가짜 친절을 주의하십시오. 도움을 줄 때도 받을 때도 의도가 순수해야 합니다." },
    { name: "SEVEN OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Pents07.jpg", meaning_reg: "열심히 일한 뒤 수확을 기다리며 성찰하고 있군요. 인내하십시오. 당신의 열매는 잘 익어가고 있습니다.", meaning_rev: "노력에 비해 보상이 적어 실망하셨나요? 방법이 틀렸거나 혹은 너무 일찍 포기하려 하고 있습니다." },
    { name: "EIGHT OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/4/49/Pents08.jpg", meaning_reg: "성실함이 당신의 가장 큰 재산입니다. 반복되는 일상 속에서 장인 정신을 발휘해 실력을 키우십시오.", meaning_rev: "목표 없는 노력이 지루하게 느껴집니다. 결과에만 급급해하지 말고 과정의 소중함을 다시 깨달으세요." },
    { name: "NINE OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Pents09.jpg", meaning_reg: "우아하고 풍요로운 독자적인 성공을 누리십시오. 스스로 일궈낸 안정이 당신을 빛나게 할 것입니다.", meaning_rev: "외적으로는 화려하나 속은 비어 있습니다. 금전적 안정이 진정한 행복을 보장하지 않음을 기억하십시오." },
    { name: "TEN OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/4/42/Pents10.jpg", meaning_reg: "가문의 영광과 부가 이어집니다. 견고한 토대 위에서 소중한 사람들과 영속적인 행복을 누리십시오.", meaning_rev: "금전 갈등으로 가족이나 동료와 멀어질 수 있습니다. 물질적 가치보다 정신적 유산을 챙기십시오." },
    { name: "PAGE OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Pents11.jpg", meaning_reg: "현실적인 새로운 계획과 공부가 시작됩니다. 신중하고 성실한 태도가 장래에 큰 부를 가져다줍니다.", meaning_rev: "현실 감각이 떨어지는 계획에 매달리고 있군요. 말로만 투자하기보다 직접 발로 뛰며 배우십시오." },
    { name: "KNIGHT OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Pents12.jpg", meaning_reg: "느리지만 가장 확실한 성장을 이룹니다. 당신의 성실함과 우직함이 결국 승리를 쟁취할 것입니다.", meaning_rev: "지나치게 보수적이고 고지식한 태도가 성장을 막습니다. 고집을 버리고 변화의 흐름을 수용하십시오." },
    { name: "QUEEN OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/8/88/Pents13.jpg", meaning_reg: "실제적이고 따뜻한 보살핌의 에너지입니다. 주변을 풍요롭게 가꾸며 안정적인 성취를 만끽하십시오.", meaning_rev: "소유욕이 집착으로 변하고 있습니다. 타인을 돈이나 가치로만 평가하지 않도록 마음을 넓히십시오." },
    { name: "KING OF PENTACLES", img: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Pents14.jpg", meaning_reg: "물질적 성공의 정점입니다. 당신의 능력은 이미 검증되었으니 여유롭게 결실을 지키고 관리하십시오.", meaning_rev: "물질적인 성공에만 매몰되어 영혼이 메말랐습니다. 돈이 당신의 인격을 대신할 수 없음을 명심하세요." }
];