const swordCards = [
    { name: "ACE OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Swords01.jpg", meaning_reg: "진실의 칼날이 번뜩입니다. 냉철한 판단력으로 복잡한 문제를 단번에 해결하십시오.", meaning_rev: "날카로운 언행이 상처를 줍니다. 혼란스러운 생각에 갇혔으니 칼을 거두고 이성을 찾으십시오." },
    { name: "TWO OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Swords02.jpg", meaning_reg: "팽팽한 대립 속에 결정을 내리지 못하고 있군요. 눈을 가린 수건을 벗고 현실을 직시하십시오.", meaning_rev: "오도 가도 못하던 교착 상태가 깨집니다. 억지라도 결론을 내야 하는 상황이니 용기를 내세요." },
    { name: "THREE OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/0/02/Swords03.jpg", meaning_reg: "피할 수 없는 슬픔은 성장의 거름이 됩니다. 아픔을 충분히 느끼고 흘려보내야 치유가 시작됩니다.", meaning_rev: "과거의 상처를 계속 헤집고 있습니다. 이제 스스로를 용서하고 고통의 굴레에서 벗어날 때입니다." },
    { name: "FOUR OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Swords04.jpg", meaning_reg: "치열한 전투 끝의 휴식입니다. 아무것도 하지 말고 몸과 마음을 정화하는 시간을 가지십시오.", meaning_rev: "억지로 움직이려 하지 마십시오. 번아웃이 오기 직전이니 강제적인 휴식이라도 취해야 합니다." },
    { name: "FIVE OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/2/23/Swords05.jpg", meaning_reg: "상처뿐인 승리입니다. 이기긴 했으나 소중한 사람을 잃었군요. 승부욕보다 관계의 가치를 살피세요.", meaning_rev: "패배를 인정하고 갈등에서 물러나십시오. 무의미한 논쟁은 당신의 영혼만 황폐하게 만들 뿐입니다." },
    { name: "SIX OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/2/29/Swords06.jpg", meaning_reg: "어려운 상황에서 서서히 벗어나고 있습니다. 조력자의 도움을 받아 더 나은 곳으로 이동하십시오.", meaning_rev: "문제를 해결하지 못한 채 몸만 피하고 있군요. 짐이 무겁더라도 근본적인 원인을 해결해야 합니다." },
    { name: "SEVEN OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/3/34/Swords07.jpg", meaning_reg: "비겁한 수단이나 편법을 쓰고 있지는 않은가요? 정면 돌파가 어렵더라도 양심을 저버리지 마십시오.", meaning_rev: "속임수가 드러나 곤혹을 치를 수 있습니다. 정직한 태도만이 현재의 위기를 극복할 유일한 길입니다." },
    { name: "EIGHT OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Swords08.jpg", meaning_reg: "스스로 만든 생각의 감옥에 갇혀 있군요. 사슬은 묶여있지 않습니다. 눈을 뜨고 걸어 나오십시오.", meaning_rev: "구속에서 벗어날 실마리를 찾았습니다. 두려움을 떨쳐내면 당신을 막을 수 있는 것은 아무것도 없습니다." },
    { name: "NINE OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Swords09.jpg", meaning_reg: "불안과 악몽이 당신을 괴롭힙니다. 일어나서 불을 켜십시오. 상상이 현실보다 더 무서운 법입니다.", meaning_rev: "걱정했던 일이 생각보다 별것 아님을 알게 됩니다. 절망의 끝에서 희망의 빛을 발견하는 운입니다." },
    { name: "TEN OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords10.jpg", meaning_reg: "최악의 상황은 끝났습니다. 바닥을 쳤으니 이제 올라갈 일만 남았군요. 고통스러운 끝은 새로운 시작입니다.", meaning_rev: "힘들었던 고비가 지나가고 회복이 시작됩니다. 죽음 같은 고요 뒤에 찾아올 새벽을 준비하십시오." },
    { name: "PAGE OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Swords11.jpg", meaning_reg: "경계심을 늦추지 마십시오. 새로운 정보에 귀를 기울이되 성급한 행동은 금물입니다. 관찰이 우선입니다.", meaning_rev: "경솔한 말 한마디가 화근이 됩니다. 정보의 진위 여부를 따지지 않고 퍼뜨리다 낭패를 볼 수 있습니다." },
    { name: "KNIGHT OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Swords12.jpg", meaning_reg: "목표를 향해 맹렬히 돌진하십시오. 지적인 통찰력과 속도감이 당신을 성공으로 이끌 것입니다.", meaning_rev: "무모한 돌진은 사고를 부릅니다. 주변 상황을 살피지 않는 독단적인 태도가 큰 장애물을 만듭니다." },
    { name: "QUEEN OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords13.jpg", meaning_reg: "공정하고 엄격한 판단이 빛나는 날입니다. 감정에 휘둘리지 말고 진실만을 좇아 결단하십시오.", meaning_rev: "냉정함이 지나쳐 독선적으로 보입니다. 정의로운 마음이 타인에게 비수가 되지 않도록 주의하십시오." },
    { name: "KING OF SWORDS", img: "https://upload.wikimedia.org/wikipedia/commons/3/33/Swords14.jpg", meaning_reg: "지적인 권위와 질서의 수호자입니다. 논리적이고 체계적인 접근이 당신의 품격을 높여줄 것입니다.", meaning_rev: "지식을 권력으로 휘두르고 있군요. 머리는 차갑되 가슴은 따뜻해야 진정한 리더가 될 수 있습니다." }
];