const wandCards = [
    { name: "ACE OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/1/11/Wands01.jpg", meaning_reg: "열정의 씨앗이 심어졌습니다. 가슴 뛰는 일을 당장 시작하십시오. 행동이 운명을 바꿉니다.", meaning_rev: "의욕만 앞서고 방향이 없습니다. 에너지가 분산되지 않도록 가장 중요한 목표에만 집중하십시오." },
    { name: "TWO OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/1/18/Wands02.jpg", meaning_reg: "더 넓은 세상을 향한 계획을 세우십시오. 당신은 이미 기반을 닦았고 이제 확장이 필요합니다.", meaning_rev: "안전한 곳에만 머물려 하고 있군요. 두려움 때문에 새로운 기회를 놓치고 있지는 않은지 보세요." },
    { name: "THREE OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Wands03.jpg", meaning_reg: "멀리서 좋은 소식이 들려옵니다. 당신의 비전이 현실화되어 결실을 맺기 위해 다가오고 있습니다.", meaning_rev: "결과가 지연되어 초조하시군요. 기초가 튼튼하다면 결국 성공하니 여유를 갖고 기다리십시오." },
    { name: "FOUR OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Wands04.jpg", meaning_reg: "축제와 안식의 시간입니다. 공들인 일의 중간 성공을 축하하며 소중한 이들과 즐거움을 나누세요.", meaning_rev: "내부의 갈등으로 평화가 흔들립니다. 가까운 사이일수록 예의를 지키고 감사를 표현해야 합니다." },
    { name: "FIVE OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Wands05.jpg", meaning_reg: "치열한 경쟁과 혼란이 예상됩니다. 하지만 이 투쟁은 성장을 위한 건강한 자극이 될 것입니다.", meaning_rev: "소모적인 논쟁에서 빠져나오십시오. 갈등을 회피하기보다 대화를 통해 질서를 찾는 것이 우선입니다." },
    { name: "SIX OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Wands06.jpg", meaning_reg: "금의환향의 카드입니다. 당신의 노력이 공개적으로 인정받고 승리를 거두게 될 것입니다.", meaning_rev: "승리 뒤의 자만심을 경계하십시오. 타인의 질투를 유발하거나 실속 없는 명예에 취할 수 있습니다." },
    { name: "SEVEN OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Wands07.jpg", meaning_reg: "유리한 고지에서 도전들을 물리치고 있군요. 신념을 굽히지 마십시오. 당신은 충분히 이길 수 있습니다.", meaning_rev: "지나치게 많은 일에 치여 버겁습니다. 포기하고 싶은 마음이 들겠지만 조금만 더 힘을 내십시오." },
    { name: "EIGHT OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Wands08.jpg", meaning_reg: "상황이 급물살을 탑니다. 지체되던 일들이 빠르게 해결되니 흐름을 타고 기민하게 움직이십시오.", meaning_rev: "성급한 행동이 일을 그르칩니다. 속도는 빠르되 방향이 틀리지 않았는지 다시 한번 체크하십시오." },
    { name: "NINE OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Wands09.jpg", meaning_reg: "마지막 고비입니다. 지쳐있지만 포기하지 마십시오. 당신은 이미 충분한 방어벽을 쌓았습니다.", meaning_rev: "방어 기제가 너무 강해져 주변을 밀어내고 있군요. 경계심을 조금 풀고 도움을 받아들여도 됩니다." },
    { name: "TEN OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Wands10.jpg", meaning_reg: "너무 많은 짐을 혼자 짊어지고 있습니다. 책임감이 당신을 누르고 있으니 짐을 나누거나 버리십시오.", meaning_rev: "한계에 도달했습니다. 무너진 뒤에는 늦으니 지금 즉시 불필요한 일들을 정리하고 휴식하십시오." },
    { name: "PAGE OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Wands11.jpg", meaning_reg: "새로운 영감과 소식이 찾아옵니다. 서툴더라도 열정적으로 도전해 보기에 아주 좋은 날입니다.", meaning_rev: "아이디어만 무성하고 실행력이 부족합니다. 소문만 무성한 소식에 휘둘리지 않도록 주의하십시오." },
    { name: "KNIGHT OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/1/16/Wands12.jpg", meaning_reg: "거침없는 에너지가 솟구칩니다. 변화와 모험을 두려워하지 말고 당신의 야망을 따라 움직이십시오.", meaning_rev: "충동적인 행동이 화를 부릅니다. 앞뒤 가리지 않는 돌진은 큰 손실을 초래하니 냉정해지십시오." },
    { name: "QUEEN OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Wands13.jpg", meaning_reg: "자신감 넘치고 매력적인 에너지가 주위를 밝힙니다. 당신의 당당함이 곧 성공의 열쇠가 될 것입니다.", meaning_rev: "질투심이나 변덕이 관계를 망칠 수 있습니다. 자신의 힘을 타인을 깎아내리는 데 쓰지 마십시오." },
    { name: "KING OF WANDS", img: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Wands14.jpg", meaning_reg: "카리스마 있는 리더의 모습입니다. 당신의 비전을 믿고 따르는 이들과 함께 원대한 목표를 이루십시오.", meaning_rev: "독재적인 태도가 갈등을 일으킵니다. 열정이 고집으로 변하지 않도록 타인의 의견을 수용하십시오." }
];